name: Lua check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v10.0.0
    - uses: leafo/gh-actions-luarocks@v4.3.0
    - name: Set up lua
      run: |
        cd filters; luarocks init
    - name: Run tests and linters
      run: |
        cd filters; luarocks test
