name: Lua check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v8.0.0
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: Set up lua
      run: |
        luarocks install busted
        luarocks install luacheck
    - name: Lint with luacheck
      run: |
        cd filters; luacheck src/*.lua --std max+busted
    - name: Test with busted
      run: |
        cd filters; busted src -p '.*.test.lua'
