name: Lua check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v5
    - uses: leafo/gh-actions-luarocks@v2
    - name: Set up lua
      run: |
        luarocks install busted
        luarocks install luacheck
    - name: Lint with luacheck
      run: |
        luacheck cli/slipbox/filters/*.lua --std max+busted
    - name: Test with busted
      run: |
        cd cli/slipbox
        busted . -p '.*.test.lua'
