# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pytest mypy
        if [ -f cli/requirements.txt ]; then pip install -r cli/requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd cli; flake8 slipbox --max-complexity=10
    - name: Lint with pylint
      run: |
        cd cli; pylint --fail-under=10 slipbox -d R0903,C0415
    - name: Run mypy
      run: |
        cd cli; mypy -p slipbox
    - name: Test with pytest
      run: |
        cd cli; pytest --cov=slipbox --cov-report=term-missing --cov-branch --verbose
